### ISSUE TITLE
Gps spoofing and fake meetups?

### ISSUE THREAD

**Issue by ubiubi18** [encointer/whitepaper#1]
i like the idea of local currencies and demurrage. I am curious for your proof of location. I just wonder how your protocol can mitigate the risk that i do gps-spoofing with multiple mobiles to set up a fake meetup with sybils at a lonely location? Gps-spoofing was a common cheat in gps-based games like "ingress" a few years back.

We can argue that local currency of gps-sybils has no value because nobody will trade it. 

But i think if it would really stay that "local" at the layer of sybil resistant close neighbors and friends... well, i think you wouldnt need another currency at all to trade favors of unconditional friendship "credit" or "basic income" with them at that close level. As soon as we want to use a local currency at a broader level, it all becomes more anonymous and the sybil problem like gps-spoofing gets more relevant again?

Anyway, i am looking forward to try it out in my City with real people. Good luck ;)

**Comment by brenzi** [comment]
The Encointer protocol doesn't rely on GPS information. It makes the following assumptions:
* 50% of the participants are honest
* participants do not know beforehand whom they are going to meet at the next ceremony

This way you can't talk your meetup buddies into meeting somewhere else or try other social engineering strategies. You could of course bootstrap your own sybil-attack currency where you have a few of your bots meet and issue money. But who would be interested in this currency? Like you said.

Check out our [threat model](http://book.encointer.org/protocol-threat-model.html) for details and attack scenarios

The Proof-of-location is based on mutual attestation and predefined meetup locations only. But thts enough if you can accept the assumptions above.

**Comment by ubiubi18** [comment]
More than 50% of participants are honest? I hope this statement is true for menkind on a more global Level, but i fear it is often not true for the sneaky early adopter mob in blockchain space. Be aware that some cryptoubi-projects allready experienced incredible surges of dishonest and greedy crowds trying to cheat and spoof whereever possible. 

Especially cryptoubi seems really attractive for Multi-Level-Marketing Gangs, because cryptoubi promises the participants free Lunch, so MLM Gangs dont even need to lie about everything, but just try to pump and dump in the most effective manner. They dont care about the idea, just about profit within a few month, even if it destroys the project. 

I think it is a henn-egg problem to get adoption of honest majority early enough which is really hard without shady crowds beeing involved. I wish you best luck and hope you prove me wrong!  I would try it if it gets real one day.
